- name: Deploy a service via docker compose
  hosts: "{{target}}"
  become: true

  vars_prompt:
  - name: target
    prompt: "Which host should this run against?"
    private: false

  roles:
    - compose-deploy